services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - ${nginxportOUT}:${nginxportIN}
    volumes:
      - ./html:/var/www/html
      - ./log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    command: >
      bash -c "apt update && apt install -y curl && nginx -g 'daemon off;'"
    networks:
      expose:
        ipv4_address: 10.0.0.10
      front:
        ipv4_address: 10.0.1.10

  loadbalancer:
    image: haproxy:latest
    container_name: haproxy
    networks:
      front:
        ipv4_address: 10.0.1.11
      back:
        ipv4_address: 10.0.2.11
    volumes:
      - ./log/haproxy:/var/log/haproxy
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    command: >
      bash -c "haproxy -f '/usr/local/etc/haproxy/haproxy.cfg' -db"
    depends_on:
      - nginx

  apache1:
    image: httpd:latest
    container_name: apache1
    command: >
      bash -c "apt update && apt install -y curl && httpd-foreground"
    networks:
      back:
        ipv4_address: 10.0.2.12
    volumes:
      - ./apache/index.html:/usr/local/apache2/htdocs/index.html

  apache2:
    image: httpd:latest
    container_name: apache2
    command: >
      bash -c "apt update && apt install -y curl && httpd-foreground"
    networks:
      back:
        ipv4_address: 10.0.2.13
    volumes:
      - ./apache/index.html:/usr/local/apache2/htdocs/index.html


networks:
  expose:
    ipam:
      config:
        - subnet: 10.0.0.0/24
  front:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back:
    ipam:
      config:
        - subnet: 10.0.2.0/24